name = "switch"
main = "src/worker.ts"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
LOG_LEVEL = "info"

[triggers]
crons = ["0 1 * * *"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
